#!/usr/bin/env php
<?php

$app = $argv[1] ?? 'dentalos';

if (in_array($app, ['api', 'web'])) {
    $command = array_slice($argv, 2);
    $path = __DIR__ . "/apps/{$app}/artisan";
    passthru("php \"{$path}\" " . implode(' ', $command));
} else {
    // Default to dentalos if not api or web
    $command = (in_array($argv[1] ?? '', ['dentalos'])) ? array_slice($argv, 2) : array_slice($argv, 1);
    $path = __DIR__ . "/dentalos/artisan";
    passthru("php \"{$path}\" " . implode(' ', $command));
}
